MattWeinberg24/cse437

- project/package-lock.json
- project/package.json
- project/server/api/add.post.ts
- project/server/api/delete.get.ts
- project/server/api/query.get.ts
- project/server/lib/firebase.ts
- project/server/lib/firestore.ts
Set up Firebase project, implemented basic query/add/delete api functionality utilizing tutorial ([Video Link](https://www.youtube.com/watch?v=eylH4KxDJJw))
> set up basic firebase api functionality

- project/app.config.ts
- project/app.vue
- project/layouts/default.vue
- project/nuxt.config.ts
- project/package-lock.json
- project/package.json
- project/pages/about.vue
- project/pages/index.vue
- project/pages/login.vue
- project/pages/profile.vue
- project/pages/review.vue
need to add Nuxt UI and Tailwind CSS w/ npm to work
> setting up hompage and login

- project/composables/useStates.ts
- project/pages/index.vue
- project/plugins/auth-middleware.ts
When fetching stuff from Firestore, try to have it in "mounted" so that it is resolved before the page renders.
Also fixed some Typescript compiler complaining issues.
> hydration fix on index

- project/components/LoginForm.vue
- project/components/RegisterForm.vue
- project/composables/auth.ts
- added check for authentication before redirect on login
- added check for authentication before redirect on register
- added rules for register to make sure user submits a password above 6 characters
> modify login and register

- project/components/RegisterForm.vue
- project/lib/db.ts
added function on register submit to add additional user info to database
> registering adds auth user to database

- project/pages/details/index.vue
- project/pages/review.vue
- added required rules to the review form
- added the db data to selection options in review form
> making all review questions required + importing database data

- project/pages/admin.vue
- project/plugins/auth-middleware.ts
Can add/edit classes/professors
Will add removing later
Temporarily removed "/admin" path rule from middleware until we figure out how to protect this page, since right now anyone can use it.
> Admin page

- project/pages/review.vue
- adjusted review page to accept the reviewed object id so querying from database is more accurate
> fix to review page to send reviewed object id instead of name

- project/components/Card.vue
- project/components/GlobalNav.vue
- project/components/LoginForm.vue
- project/components/LogoutBtn.vue
- project/components/MakeReviewBtn.vue
- project/components/RegisterForm.vue
- project/pages/details/index.vue
- project/pages/index.vue
- project/pages/profile.vue
- project/pages/review.vue
- project/plugins/vuetify.ts
- added a double verification for password during registration
- make registration flow into 2 parts to be more manageable
- added hiding/revealing capabilities on password to both login and register 
- added extra validation checks before registering a user
- factored out a logout and make a review buttons to components for easier management
> adding password verify and password hiding/revealing

- project/components/RegisterForm.vue
- project/composables/auth.ts
- project/pages/debug.vue
- project/pages/index.vue
Support for Firestore security rules (so that the code doesn't break)
* Refactored homepage logic
* Refactored register logic
* Small other changes
> making firestore rules not break the code

- project/components/Card.vue
- project/components/GlobalNav.vue
- project/components/LoginBtn.vue
- project/components/MakeReviewBtn.vue
- project/components/RegisterBtn.vue
- project/components/RegisterForm.vue
- project/components/Search.vue
- project/pages/details/index.vue
- project/pages/index.vue
- project/pages/review.vue
- refactored make a review to be on the search page itself
- added professors into search
> refactoring review

- project/components/Card.vue
- project/components/GlobalNav.vue
- project/components/LoginBtn.vue
- project/components/MakeReviewBtn.vue
- project/components/RegisterBtn.vue
- project/components/RegisterForm.vue
- project/components/Search.vue
- project/pages/details/index.vue
- project/pages/index.vue
- project/pages/profile.vue
- project/pages/review.vue
- added functionality to delete posts
- fixing some bugs from refactoring make reviews
> Added deleting posts

- project/components/Card.vue
- project/components/EditModal.vue
- project/pages/profile.vue
- finished editing function for posts
> editing function complete

- project/components/EditModal.vue
- project/components/RegisterForm.vue
- project/pages/review.vue
Used video tutorial (https://www.youtube.com/watch?v=7aDG3L-bTS8) to add serverTimestamp() values to posts. Keeps track of createdAt (for adding) and modifiedAt (for editing)
> store serverTimestamp for posts/users

- project/components/AdminBtn.vue
- project/components/GlobalNav.vue
button appears in GlobalNav that leads to admin page, if the user is admin
> admin button in navbar

- project/components/AvatarMenu.vue
- project/components/Card.vue
- project/components/GlobalNav.vue
- project/lib/db.ts
- project/pages/details/index.vue
- project/pages/profile.vue
- changed avatar menu to reflect actual user info
- adjust cards for mobile slightly
> Details summary

- project/components/ProfilePicBtn.vue
- project/lib/firebase.ts
- project/lib/storage.ts
- project/pages/debug.vue
Profile pictures are located in Firebase Storage in the "profile_pics" folder. The filename is simply the user's uid. The file is stored without a file extension (e.g. ".jpg", ".png"), but the filetype exists in the metadata so it *shouldn't* be a problem. Rules exist so a user can only edit their own profile picture. Currently there is no filesize limit, but I can add one later if necessary.
To get a profile picture from a user, call the helper function I made, getProfilePic(uid), in lib/storage.ts (a new file)
To update a profile picture from a user, use the ProfilePicBtn component. It contains all the logic for uploading the file. **MAKE SURE YOU PASS IN THE UID AS PROP "uid_prop"**
> profile pic backend, component, helper function

- project/lib/storage.ts
- project/pages/debug.vue
- project/pages/review.vue
Able to add files in a review. Currently not viewable in the reviews themselves. Created upload/download/delete helper functions in storage.ts
> Adding files to a review. Helper functions.

- project/app.vue
- project/components/Card.vue
- project/components/EditPostModal.vue
- project/components/FileChip.vue
- project/components/GlobalNav.vue
- project/components/ProfilePicBtn.vue
- project/lib/db.ts
- project/lib/storage.ts
- project/pages/index.vue
- project/pages/profile.vue
- project/pages/review.vue
- users can add attachments while making a post
- file input handler allows for single and multiple file select at once
- user can click "add files" to mark them to be uploaded to the db
- files added appear as chips at the bottom of the file handler
- chips can be clicked on to remove file from being uploaded
- all files uploaded to db once review is submitted
- similar functionality for editing the files via adding and deleting chips in the EditPostModal
- fixed some general auth bugs
> Attachments

- project/lib/friends.ts
- project/pages/friendsProfile.vue
- project/pages/index.vue
Added "friends.ts" file with various friend-related functions. index.vue now only displays own posts and those made by friends. Fixed bug in friendProfile page that prevented request from being sent (slightly refactored the logic)
> filtering posts by friends

- project/components/FileChip.vue
- project/pages/details/index.vue
- project/pages/review-general.vue
* only friend reviews appear on class/prof details page
* Removed "add files" button from review creation. Files now "added" upon selection.
* Clicking a review's file attachment opens it in a new tab instead of the current one
> only friend reviews + simplify file upload

- project/components/Avatar.vue
- project/components/Card.vue
- project/components/EditPostModal.vue
- project/lib/db.ts
- project/lib/friends.ts
- project/pages/details/index.vue
- project/pages/index.vue
- project/pages/profile.vue
- project/pages/review-general.vue
- project/pages/review.vue
- adding an additional where query to friends.ts to make sure it returns only course or professor reviews specified in reviewedObject
> adjusting filtering on details/index.vue with change in friends.ts
